buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.ow2.asm:asm:9.6'
        classpath 'org.ow2.asm:asm-commons:9.6'
    }
}

plugins {
    id 'java'
    id 'xyz.jpenilla.run-paper' version '2.3.1' apply false
    id 'com.modrinth.minotaur' version '2.8.7' apply false
    id 'com.github.jk1.dependency-license-report' version '2.2'
    id 'com.gradleup.shadow' version '8.3.5' apply false
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            name = "papermc"
            url = uri("https://repo.papermc.io/repository/maven-public/")
        }
        maven {
            name = "jitpack"
            url = uri("https://jitpack.io")
        }
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'com.gradleup.shadow'

    group = 'com.korphere.mcomnisight'
    version = System.getenv("GITHUB_REF_NAME")?.replaceAll('^v', '') ?: '1.0.0'

    ext {
        includeOshi = project.hasProperty('oshi')
    }

    dependencies {
        implementation 'com.google.code.gson:gson:2.10.1'
        compileOnly 'org.jetbrains:annotations:24.1.0'

        implementation 'org.java-websocket:Java-WebSocket:1.5.6'
        compileOnly 'com.github.oshi:oshi-core:6.6.1'
        if (project.includeOshi) {
            implementation 'com.github.oshi:oshi-core:6.6.1'
            implementation 'net.java.dev.jna:jna:5.13.0'
            implementation 'net.java.dev.jna:jna-platform:5.13.0'
        }
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
        testImplementation 'org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.110.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    test {
        useJUnitPlatform()
    }

    shadowJar {
        relocate 'org.java_websocket', 'com.korphere.mcomnisight.libs.websocket'
        if (project.includeOshi) {
            relocate 'oshi', 'com.korphere.mcomnisight.libs.oshi'
            relocate 'com.sun.jna', 'com.korphere.mcomnisight.libs.jna'
            archiveClassifier.set('full')
        } else {
            archiveClassifier.set('lite')
        }
    }

    tasks.build {
        dependsOn tasks.shadowJar
    }

    def targetJavaVersion = 21
    java {
        def javaVersion = JavaVersion.toVersion(targetJavaVersion)
        sourceCompatibility = javaVersion
        targetCompatibility = javaVersion
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
            options.release.set(targetJavaVersion)
        }
    }
}